name: Renovate
on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: "log level for renovate"
        default: "info"
        type: "string"

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      RENOVATE_VERSION: 37-slim
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        run: |
          docker run \
          --env LOG_LEVEL=${{ inputs.loglevel || 'info' }} \
          --env RENOVATE_TOKEN="${{ secrets.TOKEN }}" \
          --env RENOVATE_REPOSITORIES="$REPOSITORIES" \
          --volume /tmp:/tmp \
          --rm renovate/renovate:${{ env.RENOVATE_VERSION }}
        env:
          REPOSITORIES: 'walczakp/renovate-sbt-issue'
          # TOKEN: 'x-access-token:${{ secrets.GITHUB_TOKEN }}'
